package com.hh.hhdb_admin;

public enum CsMgrEnum {
    LOGIN, MAIN_FRAME, MONITOR, ABOUT, USR, SEQUENCE, QUERY, TREE, TOOLBAR, MENUBAR, STATUS, ATTRIBUTE,
    TABLE, TABLE_SPACE, VIEW, DATABASE, FUNCTION, TABLE_OPEN, RULE, SCHEMA, COLUMN, TRIGGER, CONSTRAINT,
    INDEX, PACKAGE, WORKSPACE, QUICK_CMD, DB_TASK, SQL_BOOK, GIS, VM, OBJ_QUERY, DELETE, DBLINK, TYPE, SYNONYM,
    CMD
}
